In [3]:
import pandas as pd

In [27]:
movie_md = pd.read_csv('movies_metadata.csv', sep=',')

In [50]:
pd.set_option('display.max_columns', 500)
pd.set_option('display.max_colwidth', -1)

In [29]:
movie_md.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45466 entries, 0 to 45465
Data columns (total 24 columns):
adult                    45466 non-null object
belongs_to_collection    4494 non-null object
budget                   45466 non-null object
genres                   45466 non-null object
homepage                 7782 non-null object
id                       45466 non-null object
imdb_id                  45449 non-null object
original_language        45455 non-null object
original_title           45466 non-null object
overview                 44512 non-null object
popularity               45461 non-null object
poster_path              45080 non-null object
production_companies     45463 non-null object
production_countries     45463 non-null object
release_date             45379 non-null object
revenue                  45460 non-null float64
runtime                  45203 non-null float64
spoken_languages         45460 non-null object
status                   45379 non-null object
tagline                  20412 non-null object
title                    45460 non-null object
video                    45460 non-null object
vote_average             45460 non-null float64
vote_count               45460 non-null float64
dtypes: float64(4), object(20)
memory usage: 8.3+ MB

In [30]:
movie_md.head()

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,popularity,poster_path,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",21.9469,/rhIRbceoE9lR4veEXuwCC2wARtG.jpg,"[{'name': 'Pixar Animation Studios', 'id': 3}]","[{'iso_3166_1': 'US', 'name': 'United States o...",1995-10-30,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415.0
1,False,NaN,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",NaN,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,17.0155,/vzmL6fP7aPKNKPRTFnZmiUfciyV.jpg,"[{'name': 'TriStar Pictures', 'id': 559}, {'na...","[{'iso_3166_1': 'US', 'name': 'United States o...",1995-12-15,262797249.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0
2,False,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",NaN,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,11.7129,/6ksm1sjKMFLbO7UY2i6G1ju9SML.jpg,"[{'name': 'Warner Bros.', 'id': 6194}, {'name'...","[{'iso_3166_1': 'US', 'name': 'United States o...",1995-12-22,0.0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92.0
3,False,NaN,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",3.85949,/16XOMpEaLWkrcPqSQqhTmeJuqQl.jpg,[{'name': 'Twentieth Century Fox Film Corporat...,"[{'iso_3166_1': 'US', 'name': 'United States o...",1995-12-22,81452156.0,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,Waiting to Exhale,False,6.1,34.0
4,False,"{'id': 96871, 'name': 'Father of the Bride Col...",0,"[{'id': 35, 'name': 'Comedy'}]",NaN,11862,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,8.38752,/e64sOI48hQXyru7naBFyssKFxVd.jpg,"[{'name': 'Sandollar Productions', 'id': 5842}...","[{'iso_3166_1': 'US', 'name': 'United States o...",1995-02-10,76578911.0,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,False,5.7,173.0

In [31]:
movie_md.isna().sum()

adult                        0
belongs_to_collection    40972
budget                       0
genres                       0
homepage                 37684
id                           0
imdb_id                     17
original_language           11
original_title               0
overview                   954
popularity                   5
poster_path                386
production_companies         3
production_countries         3
release_date                87
revenue                      6
runtime                    263
spoken_languages             6
status                      87
tagline                  25054
title                        6
video                        6
vote_average                 6
vote_count                   6
dtype: int64

In [10]:
movie_md[movie_md['title'].isna()]

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,popularity,poster_path,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
19729,False,NaN,0,"[{'id': 28, 'name': 'Action'}, {'id': 53, 'nam...",NaN,82663,tt0113002,en,Midnight Man,British soldiers force a recently captured IRA...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19730,- Written by Ørnås,0.065736,/ff9qCepilowshEtG2GYWwzt2bs4.jpg,"[{'name': 'Carousel Productions', 'id': 11176}...","[{'iso_3166_1': 'CA', 'name': 'Canada'}, {'iso...",1997-08-20,0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Midnight Man,False,6.0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29502,False,"{'id': 122661, 'name': 'Mardock Scramble Colle...",0,"[{'id': 16, 'name': 'Animation'}, {'id': 878, ...",http://m-scramble.jp/exhaust/,122662,tt2423504,ja,マルドゥック・スクランブル 排気,Third film of the Mardock Scramble series.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29503,Rune Balot goes to a casino connected to the ...,1.931659,/zV8bHuSL6WXoD6FWogP9j4x80bL.jpg,"[{'name': 'Aniplex', 'id': 2883}, {'name': 'Go...","[{'iso_3166_1': 'US', 'name': 'United States o...",2012-09-29,0,68.0,"[{'iso_639_1': 'ja', 'name': '日本語'}]",Released,NaN,Mardock Scramble: The Third Exhaust,False,7.0,12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35586,False,NaN,0,"[{'id': 10770, 'name': 'TV Movie'}, {'id': 28,...",NaN,249260,tt2622826,en,Avalanche Sharks,A group of skiers are terrorized during spring...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35587,Avalanche Sharks tells the story of a bikini ...,2.185485,/zaSf5OG7V8X8gqFvly88zDdRm46.jpg,"[{'name': 'Odyssey Media', 'id': 17161}, {'nam...","[{'iso_3166_1': 'CA', 'name': 'Canada'}]",2014-01-01,0,82.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Beware Of Frost Bites,Avalanche Sharks,False,4.3,22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [53]:
movie_md[movie_md['title'].isna()]

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,popularity,poster_path,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
19729,False,NaN,0,"[{'id': 28, 'name': 'Action'}, {'id': 53, 'name': 'Thriller'}, {'id': 18, 'name': 'Drama'}]",NaN,82663,tt0113002,en,Midnight Man,British soldiers force a recently captured IRA terrorist to cooperate with them and then assign him to go undercover with a gang of terrorists and prevent them from killing the U.S. President. But the spy isn't in long before he realizes that the first plot is but a ruse for a more sinister scheme that could result in trouble between China and Great Britain.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19730,- Written by Ørnås,0.065736,/ff9qCepilowshEtG2GYWwzt2bs4.jpg,"[{'name': 'Carousel Productions', 'id': 11176}, {'name': 'Vision View Entertainment', 'id': 11602}, {'name': 'Telescene Film Group Productions', 'id': 29812}]","[{'iso_3166_1': 'CA', 'name': 'Canada'}, {'iso_3166_1': 'LU', 'name': 'Luxembourg'}, {'iso_3166_1': 'GB', 'name': 'United Kingdom'}, {'iso_3166_1': 'US', 'name': 'United States of America'}]",1997-08-20,0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Midnight Man,False,6.0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29502,False,"{'id': 122661, 'name': 'Mardock Scramble Collection', 'poster_path': '/b5iNxidFGFT1DLLdEY3OsLlUxG2.jpg', 'backdrop_path': '/5d38jcR72TQrjAZJ4X3nxyVMIck.jpg'}",0,"[{'id': 16, 'name': 'Animation'}, {'id': 878, 'name': 'Science Fiction'}]",http://m-scramble.jp/exhaust/,122662,tt2423504,ja,マルドゥック・スクランブル 排気,Third film of the Mardock Scramble series.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29503,Rune Balot goes to a casino connected to the October corporation to try to wrap up her case once and for all.,1.931659,/zV8bHuSL6WXoD6FWogP9j4x80bL.jpg,"[{'name': 'Aniplex', 'id': 2883}, {'name': 'GoHands', 'id': 7759}, {'name': 'BROSTA TV', 'id': 7760}, {'name': 'Mardock Scramble Production Committee', 'id': 7761}, {'name': 'Sentai Filmworks', 'id': 33751}]","[{'iso_3166_1': 'US', 'name': 'United States of America'}, {'iso_3166_1': 'JP', 'name': 'Japan'}]",2012-09-29,0,68.0,"[{'iso_639_1': 'ja', 'name': '日本語'}]",Released,NaN,Mardock Scramble: The Third Exhaust,False,7.0,12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35586,False,NaN,0,"[{'id': 10770, 'name': 'TV Movie'}, {'id': 28, 'name': 'Action'}, {'id': 27, 'name': 'Horror'}, {'id': 878, 'name': 'Science Fiction'}]",NaN,249260,tt2622826,en,Avalanche Sharks,A group of skiers are terrorized during spring break by some sharks that swim through the snow.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35587,Avalanche Sharks tells the story of a bikini contest that turns into a horrifying affair when it is hit by a shark avalanche.,2.185485,/zaSf5OG7V8X8gqFvly88zDdRm46.jpg,"[{'name': 'Odyssey Media', 'id': 17161}, {'name': 'Pulser Productions', 'id': 18012}, {'name': 'Rogue State', 'id': 18013}, {'name': 'The Cartel', 'id': 23822}]","[{'iso_3166_1': 'CA', 'name': 'Canada'}]",2014-01-01,0,82.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Beware Of Frost Bites,Avalanche Sharks,False,4.3,22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [51]:
movie_md[19729:19730]['overview']

19729    British soldiers force a recently captured IRA terrorist to cooperate with them and then assign him to go undercover with a gang of terrorists and prevent them from killing the U.S. President. But the spy isn't in long before he realizes that the first plot is but a ruse for a more sinister scheme that could result in trouble between China and Great Britain.
Name: overview, dtype: object

In [56]:
movie_md_clean = movie_md.drop([19729, 19730, 29502, 29503, 35586, 35587])

In [59]:
movie_md_clean.isna().sum()

adult                    0
belongs_to_collection    40970
budget                   0
genres                   0
homepage                 37682
id                       0
imdb_id                  17
original_language        11
original_title           0
overview                 954
popularity               0
poster_path              383
production_companies     0
production_countries     0
release_date             84
revenue                  0
runtime                  257
spoken_languages         0
status                   81
tagline                  25048
title                    0
video                    0
vote_average             0
vote_count               0
dtype: int64

In [70]:
movie_md_clean.drop(['homepage', 'poster_path', 'tagline', 'overview', 'belongs_to_collection', 'imdb_id'], axis=1, inplace=True)

In [73]:
movie_md_clean = movie_md_clean[movie_md_clean['status']=='Released']

In [75]:
movie_md_clean.drop(['status'], axis=1, inplace=True)

In [77]:
movie_md_clean.isna().sum()

adult                   0
budget                  0
genres                  0
id                      0
original_language       10
original_title          0
popularity              0
production_companies    0
production_countries    0
release_date            78
revenue                 0
runtime                 251
spoken_languages        0
title                   0
video                   0
vote_average            0
vote_count              0
dtype: int64

In [92]:
movie_md_clean[movie_md_clean['release_date'].isna()]

,adult,budget,genres,id,original_language,original_title,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,title,video,vote_average,vote_count
711,False,0,[],365371,en,War Stories Our Mother Never Told Us,0.005625,[],[],NaN,0.0,95.0,[],War Stories Our Mother Never Told Us,False,0.0,0.0
734,False,0,[],215107,en,Vermont Is for Lovers,0.75,[],[],NaN,0.0,88.0,[],Vermont Is for Lovers,False,0.0,0.0
3628,False,0,[],207731,en,Boricua's Bond,0.035352,[],[],NaN,0.0,105.0,[],Boricua's Bond,False,2.0,1.0
5879,False,0,"[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'name': 'Romance'}, {'id': 10769, 'name': 'Foreign'}]",99885,en,Divine Intervention,0.001181,[],[],NaN,0.0,87.0,[],Divine Intervention,False,0.0,0.0
13839,False,750000,[],91205,en,Bling: A Planet Rock,0,[],[],NaN,0.0,90.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Bling: A Planet Rock,False,0.0,0.0
14801,False,0,[],281287,en,Dead Ahead: The Exxon Valdez Disaster,0.035294,[],[],NaN,0.0,0.0,[],Dead Ahead: The Exxon Valdez Disaster,False,5.0,1.0
16836,False,0,[],442417,en,Das Experiment 770 - Gebären auf Befehl,0,[],[],NaN,0.0,52.0,[],Das Experiment 770 - Gebären auf Befehl,False,0.0,0.0
16953,False,0,[],367647,en,Connections,0.035294,[],[],NaN,0.0,0.0,[],Connections,False,9.0,1.0
17339,False,0,"[{'id': 99, 'name': 'Documentary'}]",366044,en,Menschliches Versagen,0.294095,[],[],NaN,0.0,91.0,"[{'iso_639_1': 'de', 'name': 'Deutsch'}]",Human Failure,False,0.0,0.0
17382,False,2500000,"[{'id': 9648, 'name': 'Mystery'}, {'id': 53, 'name': 'Thriller'}]",36663,en,Dreamkiller,0.035294,[],[],NaN,0.0,110.0,[],Dreamkiller,False,5.0,1.0
18038,False,0,[],344741,pl,Pajęczarki,0,[],[],NaN,0.0,NaN,[],Pajęczarki,False,0.0,0.0
18362,False,0,[],257608,en,Khanei ruye ab,0,[],[],NaN,0.0,111.0,[],Khanei ruye ab,False,0.0,0.0
18572,False,0,"[{'id': 99, 'name': 'Documentary'}]",404471,fi,Pölynimurikauppiaat,0,[],[],NaN,0.0,NaN,[],Pölynimurikauppiaat,False,0.0,0.0
19322,False,0,[],118013,en,Endeavour,1.23367,[],[],NaN,0.0,98.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Endeavour,False,6.6,19.0
19955,False,0,[],397339,en,The Awful Truth,0,[],[],NaN,0.0,0.0,[],The Awful Truth,False,0.0,0.0
20103,False,0,[],154792,en,Electile Dysfunction: Inside the Business of American Campaigns,0,[],[],NaN,0.0,89.0,[],Electile Dysfunction: Inside the Business of American Campaigns,False,0.0,0.0
20166,False,0,[],139909,fi,Aurinkotuuli,0.000127,[],[],NaN,0.0,NaN,[],Aurinkotuuli,False,0.0,0.0
20301,False,0,[],367678,en,Enola Gay and the Atomic Bombing of Japan,0,[],[],NaN,0.0,0.0,[],Enola Gay and the Atomic Bombing of Japan,False,0.0,0.0
20631,False,120000,"[{'id': 99, 'name': 'Documentary'}]",116059,en,Laffghanistan: Comedy Down Range,0.0375,[],[],NaN,0.0,90.0,[],Laffghanistan: Comedy Down Range,False,0.0,0.0
21167,False,0,"[{'id': 28, 'name': 'Action'}, {'id': 53, 'name': 'Thriller'}, {'id': 878, 'name': 'Science Fiction'}]",93649,en,Reflection,0,[],[],NaN,0.0,91.0,[],Reflection,False,0.0,0.0
21708,False,0,[],455027,en,Dance of Outlaws,0.000127,[],[],NaN,0.0,85.0,[],Dance of Outlaws,False,0.0,0.0
21957,False,0,[],250503,en,Bad Chicken,0.007875,[],[],NaN,0.0,90.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Bad Chicken,False,0.0,0.0
22019,False,0,[],173433,en,Holes in My Shoes,0.001654,[],[],NaN,0.0,90.0,[],Holes in My Shoes,False,0.0,0.0
22798,False,0,[],158517,en,Lain ulkopuolella,0.000143,[],[],NaN,0.0,0.0,[],Lain ulkopuolella,False,0.0,0.0
24050,False,0,"[{'id': 99, 'name': 'Documentary'}]",173300,en,Getting Back to Abnormal,0.000177,[],[],NaN,0.0,92.0,[],Getting Back to Abnormal,False,0.0,0.0
24157,False,0,[],287831,en,External Affairs,0,[],[],NaN,0.0,0.0,[],External Affairs,False,0.0,0.0
24738,False,20,"[{'id': 99, 'name': 'Documentary'}]",127375,en,America's Most Haunted Inns,0,[],[],NaN,0.0,60.0,[],America's Most Haunted Inns,False,0.0,0.0
27499,False,0,[],76162,en,Stephen Fry In America - New World,0.05048,[],[],NaN,0.0,59.0,[],Stephen Fry In America - New World,False,8.0,1.0
30609,False,0,[],201913,en,Señorita Justice,0.011574,[],"[{'iso_3166_1': 'US', 'name': 'United States of America'}]",NaN,0.0,86.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Señorita Justice,False,1.0,1.0
31080,False,0,[],91527,mr,वास्तूपुरूष,0.088886,[],[],NaN,0.0,159.0,[],Vaastupurush,False,7.5,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39339,False,0,[],367053,en,Friends and Romans,0.002001,[],[],NaN,0.0,88.0,[],Friends and Romans,False,6.0,1.0
39604,False,0,[],126140,en,Digital Dharma,0.000199,[],[],NaN,0.0,90.0,[],Digital Dharma,False,0.0,0.0
40082,False,0,[],411711,en,The Last Gold,2.3e-05,[],[],NaN,0.0,0.0,[],The Last Gold,False,0.0,0.0
40142,False,0,"[{'id': 99, 'name': 'Documentary'}]",407048,en,Scott Hall: Living on a Razor's Edge,0.003921,[],[],NaN,0.0,0.0,[],Scott Hall: Living on a Razor's Edge,True,10.0,2.0
40203,False,0,[],410576,en,Bad Dad Rehab,0.000253,[],[],NaN,0.0,NaN,[],Bad Dad Rehab,False,0.0,0.0
40740,False,0,[],343227,es,El pejesapo,0.0,[],[],NaN,0.0,98.0,"[{'iso_639_1': 'es', 'name': 'Español'}]",El pejesapo,False,0.0,0.0
40781,False,0,"[{'id': 99, 'name': 'Documentary'}]",410142,en,Lo Sound Desert,0.001393,[],[],NaN,0.0,0.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Lo Sound Desert,False,10.0,1.0
41052,False,0,"[{'id': 99, 'name': 'Documentary'}, {'id': 12, 'name': 'Adventure'}]",164134,zh,Pad Yatra: A Green Odyssey,0.000253,[],"[{'iso_3166_1': 'IN', 'name': 'India'}, {'iso_3166_1': 'NP', 'name': 'Nepal'}, {'iso_3166_1': 'US', 'name': 'United States of America'}]",NaN,0.0,70.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Pad Yatra: A Green Odyssey,False,0.0,0.0
41069,False,0,[],405763,en,The Adventures of Cinderella's Daughter,6e-06,[],[],NaN,0.0,0.0,[],The Adventures of Cinderella's Daughter,True,0.0,0.0
41114,False,0,[],278544,en,Always Faithful,4.2e-05,[],[],NaN,0.0,72.0,[],Always Faithful,False,0.0,0.0
41399,False,0,[],419289,es,Allende en su laberinto,0.0,[],[],NaN,0.0,NaN,[],Allende en su laberinto,False,0.0,0.0
41718,False,0,[],216550,de,Dolpo Tulku - Heimkehr in den Himalaya,0.0,[],[],NaN,0.0,NaN,[],Dolpo Tulku - Heimkehr in den Himalaya,False,0.0,0.0
42568,False,0,[],186592,en,Winning Favour,0.0,[],[],NaN,0.0,70.0,[],Winning Favour,False,0.0,0.0
42573,False,0,[],440361,de,Whn the day had no name,0.070588,[],[],NaN,0.0,NaN,[],Whn the day had no name,False,7.0,2.0
42941,False,0,[],366561,en,Blindpassasjer,0.035294,[],[],NaN,0.0,0.0,[],Blindpassasjer,False,7.0,1.0
43377,False,0,"[{'id': 99, 'name': 'Documentary'}]",426224,en,Jedi Junior High,0.001182,[],"[{'iso_3166_1': 'US', 'name': 'United States of America'}]",NaN,0.0,75.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Jedi Junior High,False,10.0,1.0
43523,False,0,[],409926,en,Cosmos,0.282584,[],[],NaN,0.0,60.0,[],Cosmos,False,9.1,41.0
43962,False,0,[],400796,en,Irwin & Fran 2013,0.0,[],[],NaN,0.0,83.0,[],Irwin & Fran 2013,False,0.0,0.0
44014,False,0,[],441826,en,Drzace traby,6e-06,[],[],NaN,0.0,4.0,[],Shivering Trunks,False,0.0,0.0
44065,False,0,"[{'id': 99, 'name': 'Documentary'}]",452922,ru,Supermassive Black Holes,0.04662,[],"[{'iso_3166_1': 'GB', 'name': 'United Kingdom'}]",NaN,0.0,NaN,"[{'iso_639_1': 'en', 'name': 'English'}]",Supermassive Black Holes,False,7.0,1.0
44098,False,0,[],340155,en,Игра на выбывание,0.035294,[],[],NaN,0.0,386.0,[],Игра на выбывание,False,6.0,1.0
44296,False,0,"[{'id': 18, 'name': 'Drama'}]",456956,en,Neither Wolf Nor Dog,0.000308,[],[],NaN,0.0,110.0,[],Neither Wolf Nor Dog,False,10.0,1.0
44798,False,0,"[{'id': 16, 'name': 'Animation'}, {'id': 27, 'name': 'Horror'}, {'id': 878, 'name': 'Science Fiction'}]",425916,en,Salad Fingers,0.141367,[],"[{'iso_3166_1': 'GB', 'name': 'United Kingdom'}]",NaN,0.0,52.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Salad Fingers,True,8.5,4.0
44978,False,0,[],398295,pt,Mundo Cão,0.000331,[],[],NaN,0.0,0.0,[],Mundo Cão,False,0.0,0.0
45070,False,0,[],439314,en,The Garden of Afflictions 2017,0.0,[],[],NaN,0.0,0.0,[],The Garden of Afflictions 2017,False,0.0,0.0
45148,False,0,[],438910,ru,Konstruktor krasnogo tsveta -1993,0.001586,[],[],NaN,0.0,76.0,[],Engineering Red,False,6.0,2.0
45203,False,0,"[{'id': 9648, 'name': 'Mystery'}, {'id': 878, 'name': 'Science Fiction'}]",433711,en,All Superheroes Must Die 2: The Last Superhero,0.00022,[],[],NaN,0.0,74.0,"[{'iso_639_1': 'en', 'name': 'English'}]",All Superheroes Must Die 2: The Last Superhero,False,4.0,1.0
45338,False,0,[],335251,en,The Land Where the Blues Began,0.0,[],[],NaN,0.0,0.0,[],The Land Where the Blues Began,False,0.0,0.0
45410,False,0,"[{'id': 18, 'name': 'Drama'}, {'id': 80, 'name': 'Crime'}]",449131,ru,Aprel,0.008903,[],"[{'iso_3166_1': 'RU', 'name': 'Russia'}]",NaN,0.0,NaN,[],Aprel,False,6.0,1.0
45461,False,0,"[{'id': 18, 'name': 'Drama'}, {'id': 10751, 'name': 'Family'}]",439050,fa,رگ خواب,0.072051,[],"[{'iso_3166_1': 'IR', 'name': 'Iran'}]",NaN,0.0,90.0,"[{'iso_639_1': 'fa', 'name': 'فارسی'}]",Subdue,False,4.0,1.0